name: indriver_clone_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  get_it: ^8.2.0
  http: ^1.5.0
  http_parser: ^4.1.2
  image_picker: ^1.2.0
  injectable: ^2.5.1
  path: ^1.9.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
